#!/usr/bin/env bash

#
# dent - indent the output of command
#
# CHANGE LOG:
#
# v0.1   - 2019-02-24 - Morgan Aldridge <morgant@makkintosshu.com>
#                       Initial version, pulled from https://github.com/morgant/tiggit.
# LICENSE:
#
# Copyright (c) 2019, Morgan T. Aldridge. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# - Redistributions of source code must retain the above copyright notice, this 
#   list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice, 
#   this list of conditions and the following disclaimer in the documentation 
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# environment variables
DENT_CHAR="${DENT_CHAR:-  }"
DENT_LEVEL="${DENT_LEVEL:-0}"

# indent the output of command
function dent() {
  (( DENT_LEVEL++ ))

  local line
  while IFS= read -r line; do
    for (( i=0; i<${DENT_LEVEL}; i++ )); do
      echo -n "${DENT_CHAR}"
    done
    echo "${line}"
  done <<< "$($@)"

  (( DENT_LEVEL-- ))
  return $?
}

dent "$@"